version: 2

project_name: wordgate

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/wordgate/main.go
    id: "wordgate"
    binary: wordgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: allnationconnect
    name: wordgate_sdk
  prerelease: auto
  draft: false

# brews:
#   - name: wordgate
#     tap:
#       owner: allnationconnect
#       name: homebrew-wordgate
#     folder: Formula
#     homepage: "https://github.com/allnationconnect/wordgate_sdk"
#     description: "WordGate SDK CLI Tool"
#     license: "MIT"
#     test: |
#       system "#{bin}/wordgate --version"
#     install: |
#       bin.install "wordgate" 